per-namespace and per-user deployment config
templating pipeline for per-ns initialization stuff
role creation
namespace creation
convert toYAML before tpl
kick kiam after apply as workaround for now
create ClusterRoleBinds that map to the new user Group names
never destroy while creating
allow user role to fetch kubeconfig

diff --git a/pipelines/deployer/deployer.yaml b/pipelines/deployer/deployer.yaml
--- a/pipelines/deployer/deployer.yaml
+++ b/pipelines/deployer/deployer.yaml
@@ -6,6 +6,7 @@ terraform_source: &terraform_source
     bucket: cd-gsp-private-qndvvc
     region: eu-west-2
   vars:
+    account_id: ((account-id))
     account_name: ((account-name))
     cluster_name: ((cluster-name))
     cluster_domain: ((cluster-name)).((account-name)).govsvc.uk
@@ -21,9 +22,110 @@ terraform_source: &terraform_source
 
 task_image_resource: &task_image_resource
   type: docker-image
-  source: {repository: "govsvc/task-toolbox", tag: "1.0.1"}
+  source: {repository: "govsvc/task-toolbox", tag: "1.1.0"}
 
-apply_addons_task: &apply_addons_task
+generate_cluster_values: &generate_cluster_values
+  platform: linux
+  image_resource: *task_image_resource
+  run:
+    path: /bin/bash
+    args:
+    - -eu
+    - -c
+    - |
+      mkdir -p cluster-values
+      echo "fetching cluster-values file from cluster-state..."
+      jq -r '.values' ./cluster-state/metadata > ./cluster-values/values.yaml
+      cat ./cluster-values/values.yaml
+  inputs:
+  - name: cluster-state
+  outputs:
+  - name: cluster-values
+
+generate_user_values: &generate_user_values
+  platform: linux
+  image_resource: *task_image_resource
+  params:
+    ACCOUNT_ID: ((account-id))
+    CLUSTER_NAME: ((cluster-name))
+    PATH_TO_USERS: ((config-path))/users/
+  run:
+    path: /bin/bash
+    args:
+    - -eu
+    - -c
+    - |
+      cd config
+      echo "creating helm compatible values file from user data"
+      cat ${PATH_TO_USERS}/*.yaml \
+        | yq . \
+        | jq ". + {roleARN: (\"arn:aws:iam::${ACCOUNT_ID}:role/${CLUSTER_NAME}-user-\" + .name)}" \
+        | jq -s '{users: .}' \
+        | yq --yaml-output .\
+        > ../user-values/values.yaml
+      cat ../user-values/values.yaml
+  inputs:
+  - name: config
+  outputs:
+  - name: user-values
+
+generate_users_terraform: &generate_users_terraform
+  platform: linux
+  image_resource: *task_image_resource
+  params:
+    PATH_TO_USERS: ((config-path))/users/
+  run:
+    path: /bin/bash
+    args:
+    - -eu
+    - -c
+    - |
+      mkdir -p users-terraform
+      cd config
+      echo "creating terraform for user roles from user data"
+      cat ${PATH_TO_USERS}/*.yaml \
+        | yq . \
+        | jq '[{key: (.name | gsub("[^a-z-A-Z0-9]"; "-")), value: {source: "../platform/modules/gsp-user", user_name: .name, user_arn: .ARN, cluster_name: "${var.cluster_name}"}}] | from_entries' \
+        | jq -s '{module: . | add, variable: { aws_account_role_arn: { type: "string" }, cluster_name: { type: "string" } }, provider: { aws: { region: "eu-west-2", assume_role: { role_arn: "${var.aws_account_role_arn}" } } } }' \
+        > ../users-terraform/users.tf.json
+      cat ../users-terraform/users.tf.json
+  inputs:
+  - name: config
+  outputs:
+  - name: users-terraform
+
+generate_namespace_values: &generate_namespace_values
+  platform: linux
+  image_resource: *task_image_resource
+  params:
+    PATH_TO_NAMESPACES: ((config-path))/namespaces/
+  run:
+    path: /bin/bash
+    args:
+    - -eu
+    - -c
+    - |
+      echo "creating tmp dirs"
+      mkdir -p namespace-values
+      namespace_values_file="$(pwd)/namespace-values/values.yaml"
+      mkdir ns-chart
+      cd config/${PATH_TO_NAMESPACES}
+      echo "creating helm compatible values file from namespace data"
+      echo 'namespaces:' > $namespace_values_file
+      for ns in *; do
+        echo "--> ${ns}"
+        echo "- name: ${ns}" >> $namespace_values_file
+        set_namespace=".metadata.namespace=\"${ns}\""
+        combined_resources="$(cat ${ns}/*.yaml | yq . | jq $set_namespace | jq -s -c .)"
+        echo "  resources: $combined_resources" >> $namespace_values_file
+      done
+      cat $namespace_values_file
+  inputs:
+  - name: config
+  outputs:
+  - name: namespace-values
+
+apply_cluster_chart: &apply_cluster_chart
   platform: linux
   image_resource: *task_image_resource
   params:
@@ -43,116 +145,51 @@ apply_addons_task: &apply_addons_task
     - |
       echo "assuming aws deployer role..."
       eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
-
+      #
       echo "fetching kubeconfig from aws..."
       aws eks update-kubeconfig \
         --name "${CLUSTER_NAME}" \
         --kubeconfig ./kubeconfig
       export KUBECONFIG=$(pwd)/kubeconfig
-
+      #
       echo "setting default namespace to ${DEFAULT_NAMESPACE}"
       kubectl config set-context $(kubectl config get-contexts -o name) \
         --namespace "${DEFAULT_NAMESPACE}"
-
-      echo "fetching values file from state..."
-      jq -r '.values' cluster/metadata > values.yaml
-
+      #
       echo "rendering ${CHART_NAME} chart..."
       mkdir -p manifests
       helm template \
         --name "${CHART_RELEASE_NAME}" \
         --namespace "${DEFAULT_NAMESPACE}" \
-        --values values.yaml \
+        --values cluster-values/values.yaml \
+        --values user-values/values.yaml \
+        --values namespace-values/values.yaml \
         --output-dir manifests \
-        "gsp-platform/charts/${CHART_NAME}"
-
+        "platform/charts/${CHART_NAME}"
+      #
       function apply() {
         echo "applying ${1} from ${CHART_NAME} chart..."
         until kubectl apply -R -f $1; do
-          echo "apply failed retrying..."
+          echo "---> ${1} apply failed retrying in 5s..."
           sleep 5
         done
         sleep 5 # FIXME: we should do something smarter than sleep and check for success
-        echo "OK!"
+        echo "---> ${1} applied OK!"
       }
-
+      #
       apply manifests/${CHART_NAME}/templates/00-aws-auth/
       apply manifests/${CHART_NAME}/templates/01-cni/
       apply manifests/${CHART_NAME}/templates/02-istio/
       apply manifests/${CHART_NAME}/templates/03-aws-system/
       apply manifests/
-
+      #
+      # FIXME: regenerating kiam certs (each chart apply) requires restart
+      kubectl delete pod -l app=kiam -n gsp-system || echo 'WARN: tried to kick kiam and failed'
   inputs:
-  - name: cluster
-  - name: gsp-platform
-
-
-apply_namespaces_task: &apply_namespaces_task
-  platform: linux
-  image_resource: *task_image_resource
-  params:
-    ACCOUNT_ROLE_ARN: ((account-role-arn))
-    ACCOUNT_NAME: ((account-name))
-    CLUSTER_NAME: ((cluster-name))
-    AWS_REGION: eu-west-2
-    AWS_DEFAULT_REGION: eu-west-2
-    DEFAULT_NAMESPACE: default
-    PATH_TO_NAMESPACES:
-  run:
-    path: /bin/bash
-    args:
-    - -eu
-    - -c
-    - |
-      echo "assuming aws deployer role..."
-      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
-
-      echo "fetching kubeconfig from aws..."
-      aws eks update-kubeconfig \
-        --name "${CLUSTER_NAME}" \
-        --kubeconfig ./kubeconfig
-      export KUBECONFIG=$(pwd)/kubeconfig
-
-      echo "setting default namespace to ${DEFAULT_NAMESPACE}"
-      kubectl config set-context $(kubectl config get-contexts -o name) \
-        --namespace "${DEFAULT_NAMESPACE}"
-
-      echo "fetching gsp-cluster values.yaml file from state..."
-      echo "TODO: I'm pretty sure this should NOT use the full values.yaml from gsp-cluster, we only want the global bits"
-      jq -r '.values' cluster/metadata > values.yaml
-
-      # works out namespace name base on $1 filename as $name
-      # copies gsp-namespace chart and adds the custom yaml from the namespace definition in
-      # renders out the default gsp-namespace config chart
-      # copies the yaml at $1 into the rendered output
-      # applies it with -n $name
-      function apply_namespace_config {
-        name=$(basename "${1}" | cut -d '.' -f 1)
-        nschart="charts/${name}"
-        mkdir -p charts
-        cp -r "gsp-platform/charts/gsp-namespace" "${nschart}"
-        cp "${1}" "${nschart}/templates/custom-config.yaml"
-        echo "applying ${name} configuration..."
-        mkdir -p "manifests/${name}"
-        helm template \
-          --name "${name}" \
-          --namespace "${name}" \
-          --values values.yaml \
-          --output-dir "manifests/${name}" \
-          "${nschart}"
-        until kubectl apply -R -f "manifests/${name}" -n "${name}"; do
-          echo "appling namespace configuration for ${name} failed, retrying in 3s..."
-          sleep 3
-        done
-      }
-
-      for cfg in gsp-platform/${PATH_TO_NAMESPACES}/* ; do
-        apply_namespace_config "${cfg}"
-      done
-
-  inputs:
-  - name: cluster
-  - name: gsp-platform
+  - name: cluster-values
+  - name: user-values
+  - name: namespace-values
+  - name: platform
 
 
 drain_cluster_task: &drain_cluster_task
@@ -171,14 +208,14 @@ drain_cluster_task: &drain_cluster_task
     - |
       echo "assuming aws deployer role..."
       eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
-
+      #
       echo "fetching kubeconfig from aws..."
       aws eks update-kubeconfig --name "${CLUSTER_NAME}" --kubeconfig ./kubeconfig
       export KUBECONFIG=$(pwd)/kubeconfig
-
+      #
       echo "fetching cluster VPC ID..."
       CLUSTER_VPC_ID=$(aws eks describe-cluster --name "${CLUSTER_NAME}" | jq .cluster.resourcesVpcConfig.vpcId -r)
-
+      #
       echo "deleting any LoadBalancer services..."
       kubectl get svc -o json --all-namespaces | jq '.items[] | select(.spec.type == "LoadBalancer")' | kubectl delete -f - --wait
       echo "waiting for any ELBs that belong to cluster to shutdown..."
@@ -186,14 +223,14 @@ drain_cluster_task: &drain_cluster_task
       if [[ "$(echo $ELB_ARNS_JSON | jq '.LoadBalancerArns | length')" != "0" ]]; then
         aws elbv2 wait load-balancers-deleted --cli-input-json "${ELB_ARNS_JSON}"
       fi
-
+      #
       echo "checking for ASGs that belong to this cluster..."
       CLUSTER_ASGS=$(aws autoscaling describe-auto-scaling-groups | jq -r ".AutoScalingGroups[] | select( .Tags[].Key == \"kubernetes.io/cluster/${CLUSTER_NAME}\")" | jq -r .AutoScalingGroupName)
       for ASG_NAME in $CLUSTER_ASGS; do
         echo "scaling ${ASG_NAME} to zero..."
         aws autoscaling update-auto-scaling-group --auto-scaling-group-name "${ASG_NAME}" --min-size 0 --max-size 0 --desired-capacity 0
       done
-
+      #
       echo "checking if any nodes are still running ..."
       for ASG_NAME in $CLUSTER_ASGS; do
         echo "checking number of instances remaining in ${ASG_NAME}..."
@@ -204,8 +241,7 @@ drain_cluster_task: &drain_cluster_task
         fi
       done
   inputs:
-  - name: cluster
-  - name: gsp-platform
+  - name: platform
 
 resource_types:
 - name: terraform
@@ -220,12 +256,11 @@ resource_types:
     tag: "0.0.1551114195"
 
 resources:
-- name: gsp-platform
+- name: platform
   type: git # FIXME: should be github-resource
   source:
-    uri: https://github.com/alphagov/gsp-terraform-ignition.git
+    uri: ((platform-repository))
     organization: alphagov
-    repository: gsp-terraform-ignition
     github_api_token: "((github-api-token))"
     approvers:
       - "samcrang"
@@ -234,65 +269,93 @@ resources:
       - "tlwr"
       - "blairboy362"
     required_approval_count: 2
-    branch: master
+    branch: ((platform-version))
     commit_verification_keys: ((trusted-developer-keys))
-- name: cluster
+- name: config
+  type: git # FIXME: should be github-resource
+  source:
+    uri: ((config-repository))
+    organization: alphagov
+    github_api_token: "((github-api-token))"
+    approvers:
+      - "samcrang"
+      - "paroxp"
+      - "chrisfarms"
+      - "tlwr"
+      - "blairboy362"
+    required_approval_count: 2
+    branch: ((config-version))
+    commit_verification_keys: ((trusted-developer-keys))
+- name: cluster-state
   type: terraform
   source:
     <<: *terraform_source
     backend_config:
       <<: *terraform_backend_config
       key: cluster-((cluster-name)).tfstate
+- name: user-state
+  type: terraform
+  source:
+    <<: *terraform_source
+    backend_config:
+      <<: *terraform_backend_config
+      key: users-((cluster-name)).tfstate
 
 jobs:
-- name: create-cluster
+- name: deploy
   serial: true
+  serial_groups: [cluster-modification]
   plan:
-  - get: gsp-platform
+  - get: platform
     trigger: true
-  - put: cluster
+  - get: config
+    trigger: true
+  - put: cluster-state
     params:
       env_name: ((account-name))
-      terraform_source: gsp-platform/pipelines/deployer/
-- name: apply-addons
-  serial: true
-  plan:
-  - get: gsp-platform
-    trigger: true
-    passed: ["create-cluster"]
-  - get: cluster
-    trigger: true
-    passed: ["create-cluster"]
-  - task: gsp-cluster
+      terraform_source: platform/pipelines/deployer
+  - task: generate-cluster-values
     timeout: 10m
-    config: *apply_addons_task
-- name: configure-namespaces
-  serial: true
-  plan:
-  - get: gsp-platform
-    trigger: true
-    passed: ["apply-addons"]
-  - get: cluster
-    trigger: true
-    passed: ["apply-addons"]
-  - task: gsp-cluster
+    config: *generate_cluster_values
+  - task: generate-namespace-values
     timeout: 10m
-    config: *apply_namespaces_task
+    config: *generate_namespace_values
+  - task: generate-user-values
+    timeout: 10m
+    config: *generate_user_values
+  - task: generate-user-terraform
+    timeout: 10m
+    config: *generate_users_terraform
+  - put: user-state
     params:
-      PATH_TO_NAMESPACES: pipelines/examples/namespaces
-- name: destroy-cluster
+      env_name: ((account-name))
+      terraform_source: users-terraform
+  - task: apply-cluster-chart
+    timeout: 10m
+    config: *apply_cluster_chart
+- name: destroy
   serial: true
+  serial_groups: [cluster-modification]
   plan:
-  - get: gsp-platform
-  - get: cluster
-    passed: ["create-cluster"]
+  - get: config
+  - get: platform
   - task: drain-cluster
     timeout: 30m
     config: *drain_cluster_task
-  - put: cluster
+  - task: generate-user-terraform
+    timeout: 10m
+    config: *generate_users_terraform
+  - put: cluster-state
     params:
       env_name: ((account-name))
-      terraform_source: gsp-platform/pipelines/deployer/
+      terraform_source: platform/pipelines/deployer
+      action: destroy
+    get_params:
+      action: destroy
+  - put: user-state
+    params:
+      env_name: ((account-name))
+      terraform_source: users-terraform
       action: destroy
     get_params:
       action: destroy
