Deployer Pipeline that support cloudwatch test

diff --git a/pipelines/deployer/deployer.yaml b/pipelines/deployer/deployer.yaml
--- a/pipelines/deployer/deployer.yaml
+++ b/pipelines/deployer/deployer.yaml
@@ -212,6 +212,131 @@ apply_cluster_chart: &apply_cluster_chart
   - name: namespace-values
   - name: platform
 
+run_conformance_tests: &run_conformance_tests
+	  platform: linux
+	  image_resource: *task_image_resource
+	  params:
+	    ACCOUNT_ROLE_ARN: ((account-role-arn))
+	    ACCOUNT_NAME: ((account-name))
+	    CLUSTER_NAME: ((cluster-name))
+	    DEFAULT_NAMESPACE: gsp-system
+	    AWS_REGION: eu-west-2
+	    AWS_DEFAULT_REGION: eu-west-2
+	  run:
+	    path: /bin/bash
+	    args:
+	    - -eu
+	    - -c
+	    - |
+	      echo "assuming aws deployer role..."
+	      AWS_CREDS="$(aws-assume-role $ACCOUNT_ROLE_ARN)"
+	      eval "${AWS_CREDS}"
+	      echo "fetching kubeconfig from aws..."
+	      aws eks update-kubeconfig \
+	        --name "${CLUSTER_NAME}" \
+	        --kubeconfig ./kubeconfig
+	      export KUBECONFIG=$(pwd)/kubeconfig
+	      echo "setting default namespace to ${DEFAULT_NAMESPACE}"
+	      kubectl config set-context $(kubectl config get-contexts -o name) \
+	        --namespace "${DEFAULT_NAMESPACE}"
+
+	      echo "beginning conformance test..."
+	      mkdir -p plugins/e2e/results
+
+	      function cleanup() {
+	        echo "cleaning up sonobuoy..."
+	         sonobuoy delete --wait
+	      }
+	      trap 'cleanup' INT TERM EXIT
+
+	      sonobuoy run \
+	        --wait \
+	        --sonobuoy-image "gcr.io/heptio-images/sonobuoy:v0.14.2" \
+	        --plugin e2e \
+	        --e2e-focus "Pods should be submitted and removed" \
+	        --kube-conformance-image "govsvc/conformance-amd64:0.0.1559644071" \
+	        --plugin-env e2e.ALLOWED_NOT_READY_NODES=$(kubectl get nodes --selector "! node-role.kubernetes.io/worker"  --no-headers=true | wc -l) # only wait for worker nodes
+
+	      sleep 10 # wait for results to be written
+	      results=$(sonobuoy retrieve)
+	      sonobuoy e2e ${results}
+	      passed=$(sonobuoy e2e ${results} --show passed | head -n1)
+	      failed=$(sonobuoy e2e ${results} --show failed | head -n1)
+
+	      if [[ ${passed} == "passed tests: 1" && ${failed} == "failed tests: 0" ]]; then
+	        echo "SUCCESS"
+	        exit 0
+	      fi
+
+        echo "FAIL"
+        exit 1
+	  inputs:
+	  - name: cluster-values
+	  - name: user-values
+	  - name: namespace-values
+	  - name: platform
+
+run_cloudwatch_test: &run_cloudwatch_test
+	  platform: linux
+	  image_resource: *task_image_resource
+	  params:
+	    ACCOUNT_ROLE_ARN: ((account-role-arn))
+	    ACCOUNT_NAME: ((account-name))
+	    CLUSTER_NAME: ((cluster-name))
+	    DEFAULT_NAMESPACE: gsp-system
+	    AWS_REGION: eu-west-2
+	    AWS_DEFAULT_REGION: eu-west-2
+	  run:
+	    path: /bin/bash
+	    args:
+	    - -eu
+	    - -c
+	    - |
+	      echo "assuming aws deployer role..."
+	      AWS_CREDS="$(aws-assume-role $ACCOUNT_ROLE_ARN)"
+	      eval "${AWS_CREDS}"
+	      echo "fetching kubeconfig from aws..."
+	      aws eks update-kubeconfig \
+	        --name "${CLUSTER_NAME}" \
+	        --kubeconfig ./kubeconfig
+	      export KUBECONFIG=$(pwd)/kubeconfig
+	      echo "setting default namespace to ${DEFAULT_NAMESPACE}"
+	      kubectl config set-context $(kubectl config get-contexts -o name) \
+	        --namespace "${DEFAULT_NAMESPACE}"
+	      echo "beginning cloudwatch test..."
+	      mkdir -p plugins/e2e/results
+	      function cleanup() {
+	        echo "cleaning up sonobuoy..."
+	        sonobuoy delete --wait
+	      }
+	      trap 'cleanup' INT TERM EXIT
+	      sonobuoy run \
+	        --wait \
+	        --sonobuoy-image "gcr.io/heptio-images/sonobuoy:v0.14.2" \
+	        --plugin cloudwatch-test \
+	        --plugin-env cloudwatch-test.TEST_LOGS_SINCE=$(date '+%s') \
+	        --plugin-env cloudwatch-test.TEST_LOG_GROUP=${CLUSTER_NAME}.${ACCOUNT_NAME} \
+	        --kube-conformance-image "govsvc/conformance-amd64:0.0.1559644071"
+	      sonoexitcode=$?
+	      echo "Sonobuoys exit code: $sonoexitcode"
+	      sleep 10 # wait for results to be written
+	      results=$(sonobuoy retrieve) && \
+	        mkdir results && \
+	        tar xzvf $results -C results
+	      cat results/plugins/cloudwatch-test/results/*/output
+	      passed=$(grep "Passed Tests:" results/plugins/cloudwatch-test/results/something)
+	      failed=$(passed=$(grep "Failed Tests:" results/plugins/cloudwatch-test/results/something)
+	      if [[ ${passed} == "Passed Tests: 1" && ${failed} == "Failed Tests: 0" ]]; then
+	        echo "SUCCESS"
+	        exit 0
+	      fi
+	      echo "FAIL"
+	      exit 1
+	  inputs:
+	  - name: cluster-values
+	  - name: user-values
+	  - name: namespace-values
+	  - name: platform
 
 drain_cluster_task: &drain_cluster_task
   platform: linux
@@ -368,6 +493,9 @@ jobs:
   - task: apply-cluster-chart
     timeout: 10m
     config: *apply_cluster_chart
+  - task: run-cloudwatch-test
+    timeout: 10m
+    config: *run_cloudwatch_test
 - name: destroy
   serial: true
   serial_groups: [cluster-modification]
